title: "Zainab Lowe — CS 499 ePortfolio"
description: "SNHU Computer Science Capstone"

# Use the official Cayman remote theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

baseurl: "/CS-499-ePortfolio"
url: "https://zedakins.github.io"

header_pages:
  - index.md
  - code-review.md
  - artifacts/exceptions.md
